### ISSUE TITLE
Cleanup and re-organize resources/ folder

### ISSUE THREAD

**Issue by dcousineau** [phpmentoring/resources-php#14]
Low priority but we need either new structured file names or something before the folder gets unweildly

**Comment by mfrost503** [comment]
Agreed, for organization purposes would it make sense to have Exercises->{Level Folder}->{Exercise Folder} - would at least make it easier for someone to sort through all the L1 exercises.  I think it makes sense to do something sooner rather than later since there isn't a whole lot of code in there now.  It goes for anything that has a Level attached to it (Tutorials for example)

**Comment by Tocacar** [comment]
As this repo is now to contain novice, intermediate and advanced content, the L{number} format on directory/ file names could be discarded altogether.  'Novice', 'Intermediate' and 'Advanced' Level Folders containing exercises that fall within that realm of difficulty might suffice.  People have questioned on IRC how to determine which level number to assign to an exercise anyway. 

The only numbering that could usefully remain (though not strictly essential) is on solution filenames:  {ExerciseName}Solution{number}.php  What do you think?

I am happy to do the changes before the repo gets much bigger.  Just let me know how you want to proceed.

**Comment by mfrost503** [comment]
I certainly think Novice, Intermediate, Advanced is a better structure than L1, L2, etc...as far as grouping current things Novice = L1, Intermediate=L2, Advanced=anything higher?

**Comment by dcousineau** [comment]
I'm going to add a third vote for using Novice, Intermediate, etc. as opposed to L1, L2, etc. It's more immediately accessible.

We can alternatively provide a 4th classification called "Special Topics" that would sit above advanced. For example a tutorial on bayesian classifiers identifying spam would be too advanced for "Advanced" and too specialized as well and would likely site in "Special Topics"

**Comment by Tocacar** [comment]
dcousineau - your description of a 'special topics' area is the same sort of thing I had in mind for the 'spotlight' directory.  Might be more readily understandable if re-named as special topic instead.  A comment or readme for each 'special topic' item could indicate the perceived difficulty, so probably no need to sub-divide this directory (agreed?).

Just to be clear then, are we keeping the top level directories 'exercises' and 'tutorials' and within each sub-divide content into the Novice, Intermediate, Advanced level folders?  If so, I will go ahead and remove the L{number} classification from everything and reorganise.

**Comment by dcousineau** [comment]
Tocacar - Confirmed, toplevel "exercises" and "tutorials" subdivided into "Novice", "Intermediate", and "Advanced"

**Comment by Tocacar** [comment]
Restructuring completed as discussed.

**Comment by Tocacar** [comment]
Actually, just noticed that new empty directories don't get pushed... I will create an empty readme file for each so that I can push them up.

**Comment by Tocacar** [comment]
Job done.  Readme files updated also to reflect changes to structure.
