### ISSUE TITLE
L3 Rating Solution 1

### ISSUE THREAD

**Issue by mfrost503** [phpmentoring/resources-php#2]
I noticed that the Level 3 rating solution was refactored and created as Rating Solution 2.  The thing that caught me in Solution 1 was the if - else block around $partial. I was going to throw an update together for that, essentially:

```
    $partial = 0;

    if(is_float($actualRating)) {
        $partial=1;
    }
```

Thoughts?  While 2 is refactoring, someone might only see 1 and the else block is unnecessary. Also the changing between camel case with $actualRating and underscores with $star_full might be confusing. 

I just happened to stumble in here today and notice this stuff, I can issue a pull request if everyone thinks that is a good idea.  Thanks :)

**Comment by Tocacar** [comment]
I think its a great idea - please go ahead and issue a pull request.  Thanks!
